apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: streamio.azurecr.io/streamio-backend_gateway:v1
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: gateway-secrets
                key: mongo_uri
          - name: ARTICLE_URL
            value: articles-service
          - name: FEED_URL
            value: feed-service
          - name: GAME_URL
            value: reviews-service
          - name: STREAM_URL
            value: stream-service
          - name: USER_INFOS_URL
            value: userinfo-service
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway-service
            port:
              number: 30001