on: [push]

# Environment variables available to all jobs and steps in this workflow streamio.azurecr.io/streamio-backend_gateway
env:
  REGISTRY_NAME: streamio
  CLUSTER_NAME: streamioCluster
  CLUSTER_RESOURCE_GROUP: streamio
  NAMESPACE: default
  SECRET: secret-name
  APP_NAME: streamio-backend_gateway
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container Registry (ACR)
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
      working-directory: .